name: Publish to PyPI

on:
  push:
    tags:
      - "v*"   # 打 tag 才发布，比如 v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # 必须！用于 OIDC
      contents: read

    environment: pypi   # 必须和 PyPI 填的一致

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
